### ISSUE TITLE
Ensure test coverage

### ISSUE THREAD

**Issue by kirrg001** [NexesJS/mongo-knex#3]
## Problem

Before we start with coding, we should ensure that our test suite covers the most important cases for https://github.com/NexesJS/NQL/issues/1. 

## Tasks

- [x] get an overview of the existing test coverage
- [x] ensure we cover all known bugs:
  - [x]  negation
  - [x]  counting
  - [x] `and` conjunction
  - [x] `or` conjunctions

**Comment by gargol** [comment]
In my opinion, we should `.skip` new test cases and they should be unskiped as the feature is implemented. Reason: it's not the best practice to have a failing master :) and it would be nicely visible which `skips` are removed as PR's are opened for tests that are covered.
